import { lazy, Suspense, useEffect, useState } from 'react'
import { Activity, BarChart3, BookOpen, BrainCircuit, ChartNoAxesCombined, ChevronDown, CircleHelp, Database, FileSpreadsheet, FlaskConical, GitBranch, Gauge, Layers3, Menu, Pause, Play, RotateCcw, Settings2, SlidersHorizontal, Sparkles, Upload, X } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { apiUrl } from './api'
import { ExplanationView, OrderedBoostingView } from './ModelInsights'
import { AboutCatBoost } from './AboutCatBoost'
import { BoundaryExplorer } from './BoundaryExplorer'
import { TreeInspector } from './TreeInspector'
import { ExperimentRunner } from './ExperimentRunner'
import './state.css'
import './dashboard.css'

const ModelSurface3D = lazy(() => import('./ModelSurface3D').then((module) => ({ default: module.ModelSurface3D })))
import './accessibility.css'

const groups = [
  { title: 'LEARN', items: [['About CatBoost', BookOpen]] },
  { title: 'MODEL', items: [['Overview', Gauge], ['Dataset', Database], ['Ordered Boosting', Layers3]] },
  { title: 'INSPECT', items: [['Tree Visualization', GitBranch], ['Training Progress', Activity], ['Decision Boundary', ChartNoAxesCombined]] },
  { title: 'EXPLAIN', items: [['Feature Importance', BarChart3], ['SHAP Analysis', Sparkles], ['Prediction Explorer', BrainCircuit], ['3D Visualization', Layers3]] },
  { title: 'EXPERIMENT', items: [['Hyperparameter Tuning', SlidersHorizontal], ['Model Comparison', FlaskConical]] },
  { title: 'WORKSPACE', items: [['Settings', Settings2]] },
] as const
type Page = typeof groups[number]['items'][number][0]
type Dataset = { name: string; rows: number; columns: number; target: string; task: string; missing: number; features: { name: string; type: string; missing: number; unique: number }[]; preview: Record<string, unknown>[] }
type History = { iteration: number; train: number; validation: number }
type TrainResult = { task: string; metrics: Record<string, number>; iterations: number; train_history: History[]; training_time: number; importance: { feature: string; score: number }[] }
type PredictionResult = { prediction: string | number; probabilities?: Record<string, number>; contributions: { feature: string; value: unknown; shap_value: number }[] }
type ShapResult = { feature_names: string[]; shap_values: number[]; base_value: number; global_importance: { feature: string; mean_abs_shap: number }[] }
type OrderedInfo = { category: unknown; prior_count: number; prior_target_sum: number; statistic: number }
const demo: Dataset = { name: 'Telco customer churn', rows: 7043, columns: 21, target: 'Churn', task: 'classification', missing: 11, features: [{ name: 'tenure', type: 'Numerical', missing: 0, unique: 73 }, { name: 'Contract', type: 'Categorical', missing: 0, unique: 3 }, { name: 'MonthlyCharges', type: 'Numerical', missing: 0, unique: 1585 }, { name: 'InternetService', type: 'Categorical', missing: 0, unique: 3 }, { name: 'PaymentMethod', type: 'Categorical', missing: 0, unique: 4 }, { name: 'TotalCharges', type: 'Numerical', missing: 11, unique: 6531 }], preview: [] }
const history: History[] = Array.from({ length: 40 }, (_, i) => ({ iteration: (i + 1) * 5, train: .68 * Math.exp(-i / 13) + .12, validation: .72 * Math.exp(-i / 15) + .2 + Math.sin(i / 4) * .012 }))
const importance = [{ name: 'Contract', score: 82 }, { name: 'tenure', score: 67 }, { name: 'MonthlyCharges', score: 54 }, { name: 'InternetService', score: 39 }, { name: 'PaymentMethod', score: 26 }]
const cats = [{ name: 'Month-to-month', n: 3875 }, { name: 'One year', n: 1473 }, { name: 'Two year', n: 1695 }]

export default function Dashboard() {
  const [page, setPage] = useState<Page>('Overview')
  const [data, setData] = useState(demo)
  const [selectedFeature, setSelectedFeature] = useState('Contract')
  const [target, setTarget] = useState(demo.target)
  const [task, setTask] = useState('classification')
  const [method, setMethod] = useState('mean')
  const [iteration, setIteration] = useState(120)
  const [sample, setSample] = useState(14)
  const [playing, setPlaying] = useState(false)
  const [dialog, setDialog] = useState(false)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [trained, setTrained] = useState<TrainResult | null>(null)
  const [predictionResult, setPredictionResult] = useState<PredictionResult | null>(null)
  const [shapResult, setShapResult] = useState<ShapResult | null>(null)
  const [orderedInfo, setOrderedInfo] = useState<OrderedInfo | null>(null)
  const [apiStatus, setApiStatus] = useState('checking')
  const [apiDatasetLoaded, setApiDatasetLoaded] = useState(false)
  const [depth, setDepth] = useState(6)
  const [rate, setRate] = useState(.05)

  useEffect(() => { if (!playing || (data.name !== demo.name && !apiDatasetLoaded)) return; const timer = window.setInterval(() => setIteration((n) => n >= 200 ? 1 : n + 1), 180); return () => window.clearInterval(timer) }, [playing, data.name, apiDatasetLoaded])
  useEffect(() => { document.body.classList.remove('nav-open') }, [page])
  useEffect(() => {
    let active = true
    const refreshHealth = async () => {
      try {
        const response = await fetch(apiUrl('/api/health'))
        if (!response.ok) throw new Error('API health check failed')
        const health = await response.json()
        if (!active) return
        setApiStatus('connected')
        setApiDatasetLoaded(Boolean(health.dataset_loaded))
      } catch {
        if (!active) return
        setApiStatus('offline')
        setApiDatasetLoaded(false)
      }
    }
    void refreshHealth()
    const timer = window.setInterval(() => void refreshHealth(), 2500)
    return () => { active = false; window.clearInterval(timer) }
  }, [])
  useEffect(() => {
    if (data.name === demo.name || !apiDatasetLoaded) return
    const controller = new AbortController()
    const row = Math.min(Math.max(sample - 1, 0), data.rows - 1)
    fetch(apiUrl(`/api/ordered-step?iteration=${iteration}&selected_row=${row}&feature=${encodeURIComponent(selectedFeature)}`), { signal: controller.signal })
      .then((response) => response.ok ? response.json() as Promise<OrderedInfo> : null)
      .then((result) => { if (result) setOrderedInfo(result) }).catch(() => {})
    return () => controller.abort()
  }, [data.name, data.rows, selectedFeature, iteration, sample, apiDatasetLoaded])
  useEffect(() => {
    if (!trained || !apiDatasetLoaded || !data.preview.length) return
    const sampleIndex = Math.min(data.preview.length - 1, Math.max(0, sample - 1))
    const row = data.preview[sampleIndex]
    const controller = new AbortController()
    Promise.all([
      fetch(apiUrl(`/api/shap?sample=${sampleIndex}`), { signal: controller.signal }).then((response) => response.ok ? response.json() as Promise<ShapResult> : null),
      fetch(apiUrl('/api/predict'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ row }), signal: controller.signal }).then((response) => response.ok ? response.json() as Promise<PredictionResult> : null),
    ]).then(([shap, prediction]) => { if (shap) setShapResult(shap); if (prediction) setPredictionResult(prediction) }).catch(() => {})
    return () => controller.abort()
  }, [trained, sample, data, apiDatasetLoaded])
  async function upload(file?: File) {
    if (!file) return
    setBusy(true)
    try {
      const form = new FormData(); form.append('file', file)
      const response = await fetch(apiUrl('/api/dataset/upload'), { method: 'POST', body: form })
      const result = await response.json(); if (!response.ok) throw new Error(result.detail || 'Upload failed')
      setData(result); setApiDatasetLoaded(true); setTarget(result.target); setTask(result.task); setSelectedFeature(result.features.find((item: Dataset['features'][number]) => item.missing)?.name ?? result.features[0]?.name ?? ''); setTrained(null); setPage('Dataset'); setDialog(false); setMessage(`${file.name} loaded · ${result.rows.toLocaleString()} rows`)
    } catch (error) { setMessage(`${error instanceof Error ? error.message : 'Upload failed'}. Start the API to upload a CSV.`) } finally { setBusy(false) }
  }
  async function loadSample(path?: string) {
    if (!path) return
    try {
      const response = await fetch(path)
      if (!response.ok) throw new Error('Sample file could not be loaded')
      const filename = path.split('/').pop() ?? 'sample.csv'
      await upload(new File([await response.blob()], filename, { type: 'text/csv' }))
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'Sample file could not be loaded')
    }
  }
  async function impute() {
    setBusy(true)
    try {
      const response = await fetch(apiUrl('/api/dataset/impute'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ method, columns: [selectedFeature] }) }); const result = await response.json()
      if (!response.ok) throw new Error(result.detail || 'Imputation failed'); setData(result); setTrained(null); setPredictionResult(null); setShapResult(null); setMessage(`${selectedFeature} missing values filled with ${method}`)
    } catch (error) { setMessage(`${error instanceof Error ? error.message : 'Imputation failed'}. Upload a CSV first.`) } finally { setBusy(false) }
  }
  async function train() {
    setBusy(true)
    try {
      const response = await fetch(apiUrl('/api/train'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ target, task, iterations: 200, depth, learning_rate: rate }) }); const result = await response.json()
      if (!response.ok) throw new Error(result.detail || 'Training failed'); setTrained(result); setIteration(result.iterations); setMessage(`Model trained in ${result.training_time.toFixed(1)} seconds`)
    } catch (error) { setMessage(`${error instanceof Error ? error.message : 'Training failed'}. Start the API to train a model.`) } finally { setBusy(false) }
  }

  const apiSessionExpired = data.name !== demo.name && !apiDatasetLoaded
  const activeModel = apiDatasetLoaded && trained?.task === task ? trained : null
  const chart = activeModel?.train_history?.length ? activeModel.train_history : history
  const rankedFeatures = activeModel?.importance?.length ? activeModel.importance.slice(0, 5).map((item) => ({ name: item.feature, score: Math.round(item.score) })) : importance
  const score = activeModel?.metrics[task === 'regression' ? 'r2' : 'accuracy']
  const firstMetric = score === undefined ? (task === 'regression' ? '0.782' : '86.4%') : task === 'regression' ? score.toFixed(3) : `${(score * 100).toFixed(1)}%`
  const lossMetric = activeModel?.metrics[task === 'regression' ? 'rmse' : 'log_loss']
  const secondMetric = lossMetric === undefined ? '0.342' : lossMetric.toFixed(3)
  return <div className="shell">
    <aside className="sidebar"><a className="brand" href="#overview" onClick={(e) => { e.preventDefault(); setPage('Overview') }}><span className="brand-icon"><i /></span><span className="brand-copy"><b>CatBoost</b><small>Model Studio</small></span></a><button className="workspace"><span className="workspace-avatar">T</span><span><b>Teaching workspace</b><small>Personal project</small></span><ChevronDown size={14} /></button><nav>{groups.map((group) => <div className="nav-group" key={group.title}><h2>{group.title}</h2>{group.items.map(([name, Icon]) => <button key={name} className={`nav-item ${page === name ? 'selected' : ''}`} onClick={() => setPage(name)}><Icon size={16} strokeWidth={1.8} />{name}{name === 'Dataset' && data.name !== demo.name && <i className="nav-dot" />}</button>)}</div>)}</nav><div className="sidebar-bottom"><div className="api-health"><i className={apiStatus === 'connected' ? '' : 'api-offline'} />Local API <span>{apiStatus.toUpperCase()}</span></div><button className="user-profile"><span className="profile-avatar">H</span><span><b>Harshit</b><small>Student plan</small></span><ChevronDown size={14} /></button></div></aside>
    <main><header className="topbar"><button className="icon-button mobile-nav" aria-label="Open navigation" onClick={() => document.body.classList.toggle('nav-open')}><Menu size={18} /></button><div className="crumb">Workspace <span>/</span> <b>{page}</b></div><div className="top-icons"><button className="icon-button" title="Help" aria-label="Help"><CircleHelp size={17} /></button><button className="icon-button" title="Settings" aria-label="Settings" onClick={() => setPage('Settings')}><Settings2 size={17} /></button><i /><span className="profile-avatar">H</span></div></header>
    <div className="content"><section className="heading"><div><span className="eyebrow"><i /> CATBOOST MODEL STUDIO</span><h1>{page === 'Overview' ? 'Model overview' : page}</h1><p>{page === 'Overview' ? 'A closer look at how your model learns, one iteration at a time.' : describe(page)}</p></div><div className="heading-controls"><label className="select-control"><FileSpreadsheet size={14} /><select value={data.name} aria-label="Dataset" onChange={() => setDialog(true)}><option>{data.name}</option></select><ChevronDown size={13} /></label><label className="select-control task-control"><select value={task} aria-label="Task type" onChange={(e) => { setTask(e.target.value); setTrained(null) }}><option value="classification">Classification</option><option value="regression">Regression</option></select><ChevronDown size={13} /></label><button className="primary-button" onClick={train} disabled={busy}><Sparkles size={15} />{busy ? 'Working…' : trained ? 'Retrain model' : 'Train model'}</button></div></section>
    {!activeModel && data.name === demo.name && <div className="demo-notice">DEMO DATA <span>Upload a CSV to train on your own dataset.</span></div>}
    {apiSessionExpired && <div className="notice notice-error" role="status">The local API session was reset. Reload a sample CSV or upload your dataset to continue.</div>}
    {message && <div className="notice" role="status">{message}<button aria-label="Dismiss" onClick={() => setMessage('')}><X size={14} /></button></div>}
    {page === 'Overview' ? <>
      <section className="metrics">{[[task === 'regression' ? 'R² score' : 'Accuracy', firstMetric, '↑ model score'], [task === 'regression' ? 'RMSE' : 'Log loss', secondMetric, 'validation'], ['Trees built', String(activeModel?.iterations ?? 200), 'of 200'], ['Training time', activeModel ? `${activeModel.training_time.toFixed(1)}s` : '4.82s', 'last run']].map(([label, value, trend]) => <article className="metric" key={label}><div>{label}<span>···</span></div><strong>{value}</strong><small>{trend} <i>vs. last run</i></small><Sparkline /></article>)}</section>
      <section className="grid story"><Panel title="Ordered boosting" subtitle="How CatBoost learns without target leakage" tag="● LIVE" className="boost-panel"><OrderedBoostingView iteration={iteration} setIteration={setIteration} sample={sample} setSample={setSample} playing={playing} setPlaying={setPlaying} info={orderedInfo} /></Panel><Panel title="Training progress" subtitle="Loss across boosting iterations" action={<button className="subtle-button" onClick={() => setPage('Training Progress')}>Details ↗</button>}><Training data={chart} iteration={iteration} setIteration={setIteration} /><div className="legend"><span><i />Training loss</span><span><i />Validation loss</span></div></Panel></section>
      <section className="grid three"><Panel title="Feature importance" subtitle="PredictionValuesChange" action={<button className="subtle-button" onClick={() => setPage('Feature Importance')}>Explore ↗</button>}><Importance items={rankedFeatures} onSelect={(name) => { setSelectedFeature(name); setPage('SHAP Analysis') }} /></Panel><Panel title="SHAP summary" subtitle="Impact on model output" action={<button className="subtle-button" onClick={() => setPage('SHAP Analysis')}>↗</button>}><Shap /></Panel><Panel title="Decision boundary" subtitle="Two-feature classification view" action={<button className="subtle-button" onClick={() => setPage('Decision Boundary')}>↗</button>}><Boundary /></Panel></section>
      <section className="grid three bottom-grid"><Panel title="Categorical feature analysis" subtitle={`Distribution · ${selectedFeature}`} action={<button className="subtle-button" onClick={() => setPage('Dataset')}>Dataset ↗</button>}><Categories /></Panel><Panel title="Individual tree" subtitle={`Tree ${Math.ceil(iteration / 10)} · depth ${depth}`} action={<button className="subtle-button" onClick={() => setPage('Tree Visualization')}>Inspect ↗</button>}><Tree sample={sample} /></Panel><Panel title="Prediction explorer" subtitle={`Sample #${sample}`} action={<button className="subtle-button" onClick={() => setPage('Prediction Explorer')}>Open ↗</button>}><Prediction sample={sample} setSample={setSample} /></Panel></section>
    </> : <PageContent page={page} navigatePage={setPage} data={data} selectedFeature={selectedFeature} setSelectedFeature={setSelectedFeature} target={target} setTarget={(value) => { setTarget(value); setTrained(null) }} task={task} setTask={(value) => { setTask(value); setTrained(null) }} method={method} setMethod={setMethod} impute={impute} upload={upload} loadSample={loadSample} busy={busy} iteration={iteration} setIteration={setIteration} sample={sample} setSample={setSample} playing={playing} setPlaying={setPlaying} orderedInfo={apiDatasetLoaded ? orderedInfo : null} shapResult={apiDatasetLoaded ? shapResult : null} predictionResult={apiDatasetLoaded ? predictionResult : null} rankedFeatures={rankedFeatures} chartData={chart} trainedIterations={activeModel?.iterations ?? 0} depth={depth} setDepth={setDepth} rate={rate} setRate={setRate} />}
    <footer>CatBoost Visualizer <i /> Built for model transparency <span>Dataset: {data.name} <i /> {data.rows.toLocaleString()} rows</span></footer></div></main>
    {dialog && <div className="modal-shade" onMouseDown={(e) => { if (e.target === e.currentTarget) setDialog(false) }}><section className="upload-modal" role="dialog" aria-modal="true" aria-labelledby="upload-title"><button className="modal-x icon-button" aria-label="Close" onClick={() => setDialog(false)}><X size={16} /></button><span className="modal-symbol"><Upload size={19} /></span><h2 id="upload-title">Bring in a dataset</h2><p>Upload a CSV to explore columns, check missing values, and train a CatBoost model.</p><label className="drop-zone"><input type="file" accept=".csv,text/csv" onChange={(e) => upload(e.target.files?.[0])} /><Upload size={20} /><b>Choose a CSV file</b><span>CSV files up to 20 MB</span></label><button className="secondary-button cancel-button" onClick={() => setDialog(false)}>Cancel</button></section></div>}
  </div>
}

function describe(page: Page) { const map: Partial<Record<Page, string>> = { 'About CatBoost': 'Learn the ideas behind CatBoost and find your way around the model lab.', Dataset: 'Inspect schema, missingness, and category distributions before training.', 'Ordered Boosting': 'Follow ordered target statistics and tree updates across boosting rounds.', 'Tree Visualization': 'Explore split conditions, leaf values, and the selected sample path.', 'Training Progress': 'Compare training and validation metrics at every iteration.', 'Decision Boundary': 'See how the model separates classes as trees are added.', 'Feature Importance': 'Rank the features that contribute most to model predictions.', 'SHAP Analysis': 'Understand global feature effects and individual prediction contributions.', 'Prediction Explorer': 'Inspect one row, its prediction, and the model’s reasoning.', '3D Visualization': 'Explore a model response surface across two numeric features.', 'Hyperparameter Tuning': 'Run and compare controlled model experiments.', 'Model Comparison': 'Compare CatBoost with transparent baseline metrics.', Settings: 'Configure the model, data split, and visualization preferences.' }; return map[page] ?? '' }
function Panel({ title, subtitle, action, tag, className = '', children }: { title: string; subtitle: string; action?: React.ReactNode; tag?: string; className?: string; children: React.ReactNode }) { return <article className={`panel ${className}`}><header className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div>{action ?? (tag && <span className="live-tag">{tag}</span>)}</header>{children}</article> }
function Sparkline() { return <svg className="sparkline" viewBox="0 0 72 24" aria-hidden="true"><path d="M1 18 C12 18 12 13 22 15 S36 6 46 10 S59 4 71 2" /></svg> }
function Training({ data, iteration, setIteration }: { data: History[]; iteration: number; setIteration: (value: number) => void }) { return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 10, right: 5, left: -23, bottom: 0 }}><CartesianGrid stroke="#eeedf1" vertical={false} /><XAxis dataKey="iteration" tickLine={false} axisLine={false} tick={{ fill: '#92909c', fontSize: 9 }} /><YAxis domain={[0, .9]} ticks={[0, .3, .6, .9]} tickLine={false} axisLine={false} tick={{ fill: '#92909c', fontSize: 9 }} /><Tooltip contentStyle={{ border: '1px solid #e9e7ed', borderRadius: 7, fontSize: 10 }} /><Line dataKey="train" stroke="#6c4dff" strokeWidth={2.3} dot={false} /><Line dataKey="validation" stroke="#aaa8b1" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer><div className="chart-cursor" style={{ left: `${Math.min(96, Math.max(4, iteration / 2))}%` }} /><input className="chart-range" aria-label="Selected iteration" type="range" min="1" max="200" value={iteration} onChange={(event) => setIteration(Number(event.target.value))} /></div> }
function Boosting({ iteration, setIteration, sample, setSample, playing, setPlaying, feature }: { iteration: number; setIteration: (n: number) => void; sample: number; setSample: (n: number) => void; playing: boolean; setPlaying: (v: boolean) => void; feature: string }) { const labels = ['Permute rows', 'Ordered stats', 'Grow tree', 'Update residuals', 'Add to ensemble']; const active = iteration % 5; return <div className="boosting"><div className="steps">{labels.map((label, index) => <div className={index <= active ? 'current' : ''} key={label}><b>{index < active ? '✓' : `0${index + 1}`}</b>{label}</div>)}</div><div className="row-card"><div className="row-caption">PERMUTED TRAINING ROWS <span>seed 42 · round {Math.floor(iteration / 5) + 1}</span></div><div className="row-line"><small>ROW</small>{[5, 2, 8, 1, 6, 4, 3, 7].map((n) => <button key={n} className={n === sample % 8 + 1 ? 'chosen' : ''} onClick={() => setSample(n)}>{`0${n}`}</button>)}</div><div className="row-line targets"><small>Y</small>{['No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'].map((n, i) => <span key={i} className={n === 'Yes' ? 'yes' : ''}>{n}</span>)}</div><div className="stat-box"><span className="feature-monogram">{feature.slice(0, 1)}</span><span><b>Ordered target statistic</b><small>{feature} = Month-to-month · prior rows only</small></span><strong>(2 + 0.5) / (4 + 1)<b>0.500</b></strong></div></div><div className="boost-controls"><button aria-label="Previous iteration" onClick={() => setIteration(Math.max(1, iteration - 1))}>‹</button><button className="play" aria-label={playing ? 'Pause' : 'Play'} onClick={() => setPlaying(!playing)}>{playing ? <Pause size={13} /> : <Play size={13} fill="currentColor" />}</button><button aria-label="Next iteration" onClick={() => setIteration(Math.min(200, iteration + 1))}>›</button><button className="reset" aria-label="Reset" onClick={() => { setPlaying(false); setIteration(1) }}><RotateCcw size={12} /></button><label><input type="range" min="1" max="200" value={iteration} onChange={(e) => setIteration(Number(e.target.value))} /><span>Iteration <b>{iteration}</b> / 200</span></label><select aria-label="Playback speed"><option>1×</option><option>0.5×</option><option>2×</option></select></div></div> }
function Importance({ onSelect, items = importance }: { onSelect?: (name: string) => void; items?: { name: string; score: number }[] }) { return <div className="importance">{items.map((item, i) => <button key={item.name} onClick={() => onSelect?.(item.name)}><span><small>{`0${i + 1}`}</small>{item.name}</span><i><b style={{ width: `${item.score}%` }} /></i><em>{item.score}.0</em></button>)}</div> }
function Shap() { return <div className="shap">{['Contract', 'tenure', 'MonthlyCharges', 'InternetService', 'PaymentMethod'].map((name, row) => <div key={name}><span>{name}</span><i>{Array.from({ length: 8 }, (_, i) => <b key={i} style={{ left: `${12 + (i * 19 + row * 13) % 76}%`, top: `${4 + (i * 7 + row * 3) % 13}px`, background: i % 2 ? '#9f8bf8' : '#d4cef5' }} />)}</i></div>)}</div> }
function Boundary() { return <div className="boundary"><span /><svg viewBox="0 0 260 150" preserveAspectRatio="none"><path d="M10 136 C70 125 81 103 115 86 S177 65 250 15" fill="none" stroke="#6e55ed" strokeWidth="2" strokeDasharray="4 3" />{Array.from({ length: 25 }, (_, i) => <circle key={i} cx={12 + i * 47 % 236} cy={12 + i * 31 % 124} r="3" fill={i % 3 ? '#7864ed' : '#dc8c68'} stroke="white" />)}</svg><small>tenure</small><b>Monthly charges</b></div> }
function Categories() { return <div className="categories">{cats.map((item, i) => <div key={item.name}><span>{item.name}</span><i><b style={{ width: `${item.n / 42}%`, opacity: 1 - i * .18 }} /></i><strong>{item.n.toLocaleString()}</strong></div>)}</div> }
function Tree({ sample }: { sample: number }) { return <div className="tree"><svg viewBox="0 0 300 145" role="img" aria-label="Individual CatBoost tree"><path d="M150 40 L75 90 M150 40 L225 90" stroke="#d9d6e2" fill="none" /><path d="M150 40 L75 90" stroke="#7156ef" strokeWidth="2" fill="none" />{[['Contract', '≠ Two year', 150, 35], ['tenure', '< 18 months', 75, 90], ['MonthlyCharges', '> 68.5', 225, 90]].map(([title, split, x, y], i) => <g key={title as string}><rect x={(x as number) - 42} y={(y as number) - 15} width="84" height="34" rx="5" fill={i ? 'white' : '#f5f2ff'} stroke={i ? '#e7e5eb' : '#c9bbff'} /><text x={x as number} y={(y as number) - 1} textAnchor="middle">{title}</text><text x={x as number} y={(y as number) + 10} textAnchor="middle">{split}</text></g>)}</svg><span>sample #{sample} path</span></div> }
function Prediction({ sample, setSample }: { sample: number; setSample: (n: number) => void }) { return <div className="prediction"><div><span>PREDICTED CLASS</span><b>No churn</b><strong>0.82</strong></div><label>Sample row<select value={sample} onChange={(e) => setSample(Number(e.target.value))}><option value={14}>#14 · Taylor</option><option value={21}>#21 · Morgan</option><option value={37}>#37 · Jamie</option></select></label><p>Contract <i><b /></i><strong>+0.31</strong></p></div> }

type ViewProps = { page: Page; navigatePage: (page: Page) => void; data: Dataset; selectedFeature: string; setSelectedFeature: (feature: string) => void; target: string; setTarget: (target: string) => void; task: string; setTask: (task: string) => void; method: string; setMethod: (method: string) => void; impute: () => void; upload: (file?: File) => void; loadSample: (path?: string) => void; busy: boolean; iteration: number; setIteration: (iteration: number) => void; sample: number; setSample: (sample: number) => void; playing: boolean; setPlaying: (playing: boolean) => void; orderedInfo: OrderedInfo | null; shapResult: ShapResult | null; predictionResult: PredictionResult | null; rankedFeatures: { name: string; score: number }[]; chartData: History[]; trainedIterations: number; depth: number; setDepth: (depth: number) => void; rate: number; setRate: (rate: number) => void }
function PageContent(props: ViewProps) {
  const { page, data } = props
  const selectedMissingCount = data.features.find((item) => item.name === props.selectedFeature)?.missing ?? 0
  if (page === 'About CatBoost') return <AboutCatBoost onNavigate={props.navigatePage} />
  if (page === 'Dataset') return <>
    <section className="metrics">{[['Rows', data.rows.toLocaleString()], ['Features', String(data.columns - 1)], ['Missing values', String(data.missing)], ['Categorical', String(data.features.filter((item) => item.type === 'Categorical').length)]].map(([label, value]) => <article className="metric" key={label}><div>{label}</div><strong>{value}</strong><small>dataset profile</small></article>)}</section>
    <section className="sample-dataset-bar"><label>Try a sample CSV<select defaultValue="" disabled={props.busy} onChange={(event) => props.loadSample(event.target.value)}><option value="">Choose an example…</option><option value="/samples/customer-churn.csv">Customer churn · classification</option><option value="/samples/house-prices.csv">House prices · regression</option><option value="/samples/flower-species.csv">Flower species · multiclass</option></select></label><p>Examples include missing values for imputation practice.</p></section>
    <section className="grid detail-grid"><Panel title="Dataset explorer" subtitle={`${data.name} · feature profiles`} className="wide"><div className="table-toolbar"><label>Target<select value={props.target} onChange={(e) => props.setTarget(e.target.value)}>{data.features.map((item) => <option key={item.name}>{item.name}</option>)}</select></label><label>Task<select value={props.task} onChange={(e) => props.setTask(e.target.value)}><option value="classification">Classification</option><option value="regression">Regression</option></select></label><label className="upload-inline"><Upload size={13} /> Upload CSV<input type="file" accept=".csv,text/csv" onChange={(e) => props.upload(e.target.files?.[0])} /></label></div><div className="table-scroll"><table><thead><tr><th>FEATURE</th><th>TYPE</th><th>UNIQUE</th><th>MISSING</th></tr></thead><tbody>{data.features.map((item) => <tr key={item.name} onClick={() => props.setSelectedFeature(item.name)} className={props.selectedFeature === item.name ? 'row-active' : ''}><td>{item.type === 'Categorical' ? 'Aa' : '#'} &nbsp;{item.name}</td><td>{item.type}</td><td>{item.unique.toLocaleString()}</td><td className={item.missing ? 'warn' : ''}>{item.missing}</td></tr>)}</tbody></table></div></Panel><Panel title="Missing value treatment" subtitle={`${data.missing} missing cells detected`}><div className="impute"><b>{props.selectedFeature || 'Select a feature'}</b><small>{selectedMissingCount} missing values{selectedMissingCount === 0 ? ' · already complete' : ''}</small><label>Fill strategy<select value={props.method} onChange={(e) => props.setMethod(e.target.value)}><option value="mean">Mean · numeric</option><option value="median">Median · numeric</option><option value="mode">Mode · any type</option></select></label><p>Mean and median apply to numeric columns. Mode also supports categorical values.</p><button className="primary-button" onClick={props.impute} disabled={props.busy || !data.preview.length || selectedMissingCount === 0}>{props.busy ? 'Applying…' : 'Fill missing values'}</button>{!data.preview.length && <small className="api-hint">Upload a CSV to apply imputation.</small>}</div></Panel></section>
    <Panel title="Sample records" subtitle="Preview of the active dataset"><div className="table-scroll"><table><thead><tr>{data.features.slice(0, 6).map((item) => <th key={item.name}>{item.name.toUpperCase()}</th>)}</tr></thead><tbody>{(data.preview.length ? data.preview.slice(0, 5) : [{ tenure: 1, Contract: 'Month-to-month', MonthlyCharges: 29.85, InternetService: 'DSL', PaymentMethod: 'Electronic check', TotalCharges: 29.85 }]).map((row, i) => <tr key={i}>{data.features.slice(0, 6).map((item) => <td key={item.name}>{String(row[item.name] ?? '—')}</td>)}</tr>)}</tbody></table></div></Panel>
  </>
  if (page === 'Ordered Boosting') return <section className="grid detail-grid"><Panel title="Ordered boosting lab" subtitle="Target statistics use only eligible preceding rows" className="wide"><Boosting iteration={props.iteration} setIteration={props.setIteration} sample={props.sample} setSample={props.setSample} playing={false} setPlaying={() => {}} feature={props.selectedFeature} /></Panel><Panel title="Statistic inspector" subtitle={props.selectedFeature}><div className="stat-detail"><small>ORDERED TARGET RATE</small><strong>0.500</strong><p>2 positive targets across 4 eligible preceding rows, with a prior of 0.5.</p><code>(2 + 0.5) / (4 + 1)</code></div></Panel></section>
  if (page === 'Training Progress') return <section className="grid detail-grid"><Panel title="Loss over boosting rounds" subtitle="Training and validation · linked to the overview" className="wide"><Training data={history} iteration={props.iteration} setIteration={props.setIteration} /><div className="legend"><span><i />Training loss</span><span><i />Validation loss</span></div></Panel><Panel title="Selected iteration" subtitle={`Round ${props.iteration}`}><div className="stat-detail"><small>VALIDATION LOSS</small><strong>{(.2 + .52 * Math.exp(-props.iteration / 75)).toFixed(3)}</strong><p>Best validation round <b>164</b><br />Early stopping patience <b>30 rounds</b></p></div></Panel></section>
  if (page === 'Feature Importance') return <section className="grid detail-grid"><Panel title="Importance ranking" subtitle="Select a feature to open its SHAP analysis" className="wide"><Importance onSelect={props.setSelectedFeature} /></Panel><Panel title="Importance definition" subtitle="Available model scores"><div className="option-list"><button className="option-active">PredictionValuesChange <small>Default</small></button><button>LossFunctionChange</button><button>InternalFeatureImportance</button></div></Panel></section>
  if (page === 'SHAP Analysis') return <Panel title="Global and local explanation" subtitle="Feature impact and selected-row prediction contributions"><ExplanationView shap={props.shapResult} prediction={props.predictionResult} sample={props.sample} setSample={props.setSample} /></Panel>
  if (page === 'Prediction Explorer') return <section className="grid detail-grid"><Panel title={`Prediction · sample #${props.sample}`} subtitle="Edit feature values to inspect their effect" className="wide"><div className="prediction-detail"><div><small>PREDICTED CLASS</small><strong>No churn</strong><b>82% confidence</b></div><label>Sample index<input type="number" value={props.sample} onChange={(e) => props.setSample(Number(e.target.value))} /></label><label>Contract<select><option>Month-to-month</option><option>One year</option><option>Two year</option></select></label><label>Tenure in months<input type="number" defaultValue="34" /></label><label>Monthly charges<input type="number" defaultValue="56.95" /></label></div><div className="contributions">{[['Contract', '+0.31'], ['tenure', '+0.19'], ['MonthlyCharges', '−0.12'], ['InternetService', '+0.07']].map(([name, value]) => <div key={name}><span>{name}</span><i><b /></i><strong>{value}</strong></div>)}</div></Panel><Panel title="Selected tree path" subtitle={`Tree ${Math.ceil(props.iteration / 10)} · sample #${props.sample}`}><Tree sample={props.sample} /></Panel></section>
  if (page === 'Tree Visualization') return <section className="grid detail-grid"><Panel title={`Tree ${Math.ceil(props.iteration / 10)}`} subtitle={`Boosting round ${props.iteration} · sample path highlighted`} className="wide"><Tree sample={props.sample} /><TreeInspector treeId={Math.min(Math.max(0, props.iteration - 1), Math.max(0, props.trainedIterations - 1))} trained={props.trainedIterations > 0} /></Panel><Panel title="Node details" subtitle="Selected model tree"><div className="stat-detail"><small>SELECTED ITERATION</small><strong>{props.iteration}</strong><p>The tree view shows the selected sample context and fitted CatBoost split data when a model is available.</p></div></Panel></section>
  if (page === 'Decision Boundary') return <section className="grid detail-grid"><Panel title="Boundary evolution" subtitle="Prediction regions and observations at the selected iteration" className="wide"><BoundaryExplorer features={data.features} target={props.target} iteration={props.iteration} setIteration={props.setIteration} task={props.task} /></Panel><Panel title="Selected snapshot" subtitle={`Iteration ${props.iteration}`}><div className="stat-detail"><small>MODEL CHECKPOINT</small><strong>{props.iteration}</strong><p>The iteration slider is shared with Ordered Boosting and Training Progress.</p></div></Panel></section>
  if (page === '3D Visualization') return <section className="surface-page-content"><header className="surface-page-heading"><div><span>MODEL RESPONSE · 3D</span><h2>3D Model View</h2><p>Explore how predicted probability or value changes across two numeric features.</p></div><span className="surface-task-tag">{props.task === 'regression' ? 'PREDICTED VALUE' : 'PREDICTED PROBABILITY'}</span></header><Suspense fallback={<div className="surface-loading">Loading Three.js model view…</div>}><ModelSurface3D features={data.features} target={props.target} task={props.task} iteration={props.iteration} setIteration={props.setIteration} trainedIterations={props.trainedIterations} /></Suspense></section>
  if (page === 'Hyperparameter Tuning') return <ExperimentRunner target={props.target} task={props.task} depth={props.depth} setDepth={props.setDepth} rate={props.rate} setRate={props.setRate} />
  if (page === 'Model Comparison') return <section className="grid detail-grid"><Panel title="Shared validation split" subtitle="Same dataset, target, split, and metric" className="wide"><div className="table-scroll"><table><thead><tr><th>MODEL</th><th>ACCURACY</th><th>LOG LOSS</th><th>TIME</th></tr></thead><tbody><tr><td>CatBoost</td><td>86.4%</td><td>0.342</td><td>4.8s</td></tr><tr><td>Logistic regression</td><td>81.2%</td><td>0.418</td><td>0.2s</td></tr><tr><td>Random forest</td><td>83.7%</td><td>0.391</td><td>1.6s</td></tr></tbody></table></div></Panel><Panel title="Metric comparison" subtitle="Accuracy · higher is better"><Categories /></Panel></section>
  return <section className="grid detail-grid"><Panel title="Model defaults" subtitle="Used for the next training run"><div className="setting-fields"><label>Task type<select value={props.task} onChange={(e) => props.setTask(e.target.value)}><option value="classification">Classification</option><option value="regression">Regression</option></select></label><label>Target column<select value={props.target} onChange={(e) => props.setTarget(e.target.value)}>{data.features.map((item) => <option key={item.name}>{item.name}</option>)}</select></label><label>Animation speed<select><option>1× · balanced</option><option>0.5× · slow</option><option>2× · fast</option></select></label><label>Random seed<input type="number" defaultValue="42" /></label></div></Panel><Panel title="Display preferences" subtitle="Workspace behavior"><div className="setting-fields"><label className="toggle">Compact charts<input type="checkbox" /></label><label className="toggle">Reduce motion<input type="checkbox" /></label><label>Data split<select><option>80% train · 20% validation</option></select></label></div></Panel></section>
}